version: '3.9'

networks:
  tm-network:
    name: tm-network

services:
  api:
    build: TaskManager.Api/
    container_name: api
    restart: always
    ports:
      - "8080:443"
    depends_on:
      - db-server
    networks: 
      - tm-network
    environment: 
      - ASPNETCORE_ENVIRONMENT = Docker
  db-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db-server
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SomeStr0ngPassw0rd
      - MSSQL_TCP_PORT=1433
    ports: 
      - "1400:1433"
    networks: 
      - tm-network